### ISSUE TITLE
Running Model Analyzer and Triton Server on separate host machines

### ISSUE THREAD

**Issue by msalehiNV** [triton-inference-server/model_analyzer#110]
From the user:

"I am running the model analyzer in remote mode. One thing I am not clear is does the model analyzer and triton server needs to be run on same host? Current setup I am trying is different host machine running model-analyzer and triton inference server running on AKS cluster GPU node. With this setup I am getting error that GPUs are not matching for model-analyzer and triton. Attaching error log."

Error log can be found here:

[error.log](https://github.com/triton-inference-server/model_analyzer/files/6268059/error.log)

**Comment by Tabrizian** [comment]
@msalehiNV It looks like the remote Triton server is not running on a GPU node. Currently, Model Analyzer requires both Triton Server and Model Analyzer to run on the same node.
