### ISSUE TITLE
Installation instructions perf_analyzer

### ISSUE THREAD

**Issue by msaroufim** [triton-inference-server/model_analyzer#126]
I tried running the quick start instructions using docker containers on the deep learning AMI on AWS and ran into this error which I'm suspecting is my fault

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.
```

So I tried to look at the pip instructions instead and got stuck at this step

```
$ ./build_wheel.sh <path to perf_analyzer> true

```

And it seems like I there's a missing step referencing that Triton server needs to be setup as well https://github.com/triton-inference-server which would add the ```perf_analyzer``` to `$PATH` in which case it makes sense to to remove it as user requirement in the script so it would just be 

```$ ./build_wheel.sh```

and also drop the `True` since you do mention that it's Linux specific later in the doc

**Comment by aramesh7** [comment]
@msaroufim  The reason for including the path to `perf_analyzer` as a user requirement in the script was to be able to build model analyzer with custom `perf_analyzer` builds. However, perhaps we should have a default so that the requirement can be left out if its on the $PATH.  Thank you for the comment! We will definitely look into this.

**Comment by matthewkotila** [comment]
Hi @msaroufim, hope you're doing well. It's been quite a while since this issue was opened. I just wanted to check--is this issue resolved?

**Comment by msaroufim** [comment]
Hi @matthewkotila it's been a while since I tried, lemme close this for now and reopen if needed
