### ISSUE TITLE
the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by rotorliu** [triton-inference-server/model_analyzer#143]
Run the Model Analyzer inside the container with:
$ model-analyzer -m /quick_start_repository -n add_sub --triton-launch-mode=local --export-path=analysis_results

The error message is as title.

My GPU card is Nvidia Titan X (Pascal).

**Comment by Tabrizian** [comment]
Can you please try the latest CUDA Driver? Your CUDA version and driver should look like below:

```
Driver Version: 465.19.01    CUDA Version: 11.3
```

**Comment by rotorliu** [comment]
It's OK.
The gpu driver is updated.

**Comment by rotorliu** [comment]
Thank you
