### ISSUE TITLE
Fail to analyze ensemble model: "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields

### ISSUE THREAD

**Issue by riverliuc** [triton-inference-server/model_analyzer#162]
When I use model-analyzer to analyze a ensemble model with local luanch mode, it always fails with following error:

```bash
root@dl:/inference# model-analyzer profile --checkpoint-directory checkpoints -m $PWD/model_repo --profile-models quartznet-ensemble --output-model-repository-path=/output_repo/temp --override-output-model-repository --client-protocol grpc --run-config-search-max-concurrency 800 --run-config-search-max-instance-count 2 --run-config-search-max-preferred-batch-size 64

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 538, in _ConvertFieldValuePair
    raise ParseError('Message type "{0}" should not have multiple '
google.protobuf.json_format.ParseError: Message type "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 315, in main
    analyzer.profile(client=client)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 104, in profile
    self._model_manager.run_model(model=model)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/model_manager.py", line 84, in run_model
    self._run_model_with_search(model)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/model_manager.py", line 138, in _run_model_with_search
    self._run_model_config_sweep(model, search_model_config=True)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/model_manager.py", line 167, in _run_model_config_sweep
    self._run_config_generator.generate_run_config_for_model_sweep(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/config/run/run_config_generator.py", line 98, in generate_run_config_for_model_sweep
    model_config = ModelConfig.create_from_dictionary(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/model/model_config.py", line 117, in create_from_dictionary
    protobuf_message = json_format.ParseDict(model_dict,
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 599, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields.
```

The model repository I used can be downloaded [here](https://drive.google.com/file/d/1zsfFirbzejTIDdRLM-a6fkHxAzU41ale/view?usp=sharing).

**Comment by Tabrizian** [comment]
@riverliuc Ensemble models are not supported yet in Model Analyzer. You can only use single-stage models in Model Analyzer.

**Comment by okanlv** [comment]
Hey @Tabrizian,
Do you have any update on ensemble model support?

**Comment by Tabrizian** [comment]
@okanlv We don't have any updates regarding the ensemble support. We'll update this issue as soon as more information is available.

**Comment by dhaval24** [comment]
Is ensemble models now supported for model-analyzer?

**Comment by tgerdesnv** [comment]
Not yet. We are working on it.

**Comment by dhaval24** [comment]
Do you have an expected timeline when this will be supported ?

**Comment by msalehiNV** [comment]
@dhaval24  it's on our short term roadmap since it is a high priority feature. I can share a more granular timeline with you over the email thread we have

**Comment by jmuppave** [comment]
I see in 23:01 ensemble models are supported. However I am facing the same error. 

`google.protobuf.json_format.ParseError: Message type "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields.`

I am using 23:01 model analyzer but the triton server is 22:07.

**Comment by tgerdesnv** [comment]
@jmuppave @riverliuc Do either of you have more recent repro? The original repro instructions are too old to use.

**Comment by tgerdesnv** [comment]
>I see in 23:01 ensemble models are supported.

@jmuppave Ensemble model support is in the repository, but was not in 23.01 release. It will be in the 23.02 release which should come out in the next few days.

**Comment by nv-braf** [comment]
23.02 has been released. Ensemble support is available

**Comment by jmuppave** [comment]
Hi, 

I have started using 23.02 still facing the same issue:


`
[Model Analyzer] Creating model config: ensemble_xyz_config_default

[Model Analyzer] Model ensemble_xyz_config_default load failed: [StatusCode.INTERNAL] failed to load 
                             'ensemble_xyz_config_default', no version is available

[Model Analyzer] Found existing model config: ensemble_xyz_config_0

[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]

[Model Analyzer]   Setting max_batch_size to 1

[Model Analyzer]   Enabling dynamic_batching

[Model Analyzer] Saved checkpoint to /data/model_analyzer_output/checkpoints/3.ckpt

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 559, in _ConvertFieldValuePair
    raise ParseError('Message type "{0}" should not have multiple '
google.protobuf.json_format.ParseError: Message type "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields at "ModelConfig".
`

**Comment by nv-braf** [comment]
Please delete your checkpoint and start a fresh run. Hopefully that will resolve the issue you are seeing.

**Comment by jmuppave** [comment]
Thanks, it does the trick. However, I am facing another issue. My ensemble config is similar to ensemble example in [architecture](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/architecture.md)

Here is the entire log:

`[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] Pulling docker image nvcr.io/nvidia/tritonserver:22.07-py3
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
[Model Analyzer]
[Model Analyzer] Starting quick mode search to find optimal configs
[Model Analyzer]
[Model Analyzer]
[Model Analyzer] Creating model config: xyz_preprocess_config_default
[Model Analyzer]
[Model Analyzer]
[Model Analyzer] Creating model config: xyz_config_default
[Model Analyzer]
[Model Analyzer]
[Model Analyzer] Creating model config: xyz_postprocess_config_default
[Model Analyzer]
[Model Analyzer] Model ensemble_xyz_config_default load failed: [StatusCode.INTERNAL] failed to load 'ensemble_xyz_config_default', no version is available
[Model Analyzer]
[Model Analyzer] Creating model config: xyz_preprocess_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer]
[Model Analyzer]
[Model Analyzer] Creating model config: xyz_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer]

[Model Analyzer] Creating model config: xyz_postprocess_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer]
[Model Analyzer] Model ensemble_xyz_config_0 load failed: [StatusCode.INTERNAL] failed to load 'ensemble_xyz_config_0', no version is available
[Model Analyzer]
[Model Analyzer] Done with quick mode search. Gathering concurrency sweep measurements for reports
[Model Analyzer]
[Model Analyzer]
[Model Analyzer] Done gathering concurrency sweep measurements for reports
[Model Analyzer]
[Model Analyzer] Saved checkpoint to /data/model_analyzer_output/checkpoints/0.ckpt
[Model Analyzer] Profile complete. Profiled 0 configurations for models: []
[Model Analyzer]
[Model Analyzer] WARNING: Inference output field "perf_throughput", has no data
[Model Analyzer] WARNING: Inference output field "perf_latency_p99", has no data
[Model Analyzer] Exporting server only metrics to /data/model_analyzer_output/exports/results/metrics-server-only.csv
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: No data found for model ensemble_xyz, skipping export summary.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
`

**Comment by jmuppave** [comment]
Thanks, logging helped. It was an issue with loading custom .so file.
