### ISSUE TITLE
Why force set DEPENDENCY_DIR to empty in setup.py file

### ISSUE THREAD

**Issue by BobLiu20** [triton-inference-server/model_analyzer#166]
Check this link. 

https://github.com/triton-inference-server/model_analyzer/blob/23b7017af3cf4c316b7c13c7df20cb6901745b41/setup.py#L34

**Comment by aramesh7** [comment]
Good catch, we will address this.

**Comment by aramesh7** [comment]
Closing as it was fixed in #174
