### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/model_analyzer#17]
I am trying to use memory analyzer for the `resnet50_netdef` model. It seems that I can start the tritonserver but cannot load the model. What may be the problem here?
```bash
kingsleyl@prm-dgx-05:/gpfs/fs1/kingsley/server/docs/examples$ docker run -v /var/run/docker.sock:/var/run/docker.sock -v /gpfs/fs1/kingsley/server/docs/examples/embed_model_repository:/models -v /gpfs/fs1/kingsley/server/docs/examples/results:/results --net=host memory-analyzer:latest --batch 1,2,4 --concurrency 1,2,4 --model-names resnet50_netdef --model-folder /models --export --export-path /results/
Failed to load resnet50_netdef on inference server: skipping model

Server Only:
Model                         Batch               Concurrency         Throughput          Max Memory Util(%)  Max GPU Util(%)     Max BAR1(MB)        Max Framebuffer(MB)
triton-server                 0                   0                   0 infer/sec         0                   0                   8                   308

Models:
Model                         Batch               Concurrency         Throughput          Max Memory Util(%)  Max GPU Util(%)     Max BAR1(MB)        Max Framebuffer(MB)
```

By the way, I can start the tritonserver with `resnet50_netdef` model successfully in the environment inside the `nvcr.io/nvidia/tritonserver:20.09-py3` container.

**Comment by dyastremsky** [comment]
This error typically means that the Triton client is not able to find a matching model in the directory loaded onto Triton server.

My first check would be that `/gpfs/fs1/kingsley/server/docs/examples/embed_model_repository` and `resnet50_netdef` are the same directory and name you are using to load the model when running Triton standalone. It sounds like they are. My second check would be that Triton server is not already running. There is a check for that in Memory Analyzer, but it may not apply with the new APIs in the newer, unsupported versions of Triton. If you have a running instance of Triton (or anything using ports 8000-8002), stop it while running Memory Analyzer.

Please send an update on whether those resolve the error. Also, congratulations on getting Memory Analyzer working! If you found the error with starting DCGM, please let me know.

**Comment by KingsleyLiu-NV** [comment]
> This error typically means that the Triton client is not able to find a matching model in the directory loaded onto Triton server.
> 
> My first check would be that `/gpfs/fs1/kingsley/server/docs/examples/embed_model_repository` and `resnet50_netdef` are the same directory and name you are using to load the model when running Triton standalone. It sounds like they are. My second check would be that Triton server is not already running. There is a check for that in Memory Analyzer, but it may not apply with the new APIs in the newer, unsupported versions of Triton. If you have a running instance of Triton (or anything using ports 8000-8002), stop it while running Memory Analyzer.
> 
> Please send an update on whether those resolve the error. Also, congratulations on getting Memory Analyzer working! If you found the error with starting DCGM, please let me know.

I have checked as per your suggestions but still get the same error.

**Comment by KingsleyLiu-NV** [comment]
By the way, I still cannot get Memory Analyzer working on my personal workstation with 2080Ti. The message above is on DGX-1.

**Comment by dyastremsky** [comment]
Found it! You actually need to use the absolute path to the model directory thrice in the command for now, due to the way Docker is used here. Updates bolded:
`docker run -v /var/run/docker.sock:/var/run/docker.sock -v /gpfs/fs1/kingsley/server/docs/examples/embed_model_repository**:/gpfs/fs1/kingsley/server/docs/examples/embed_model_repository** -v /gpfs/fs1/kingsley/server/docs/examples/results:/results --net=host memory-analyzer:latest --batch 1,2,4 --concurrency 1,2,4 --model-names resnet50_netdef --model-folder **/gpfs/fs1/kingsley/server/docs/examples/embed_model_repository** --export --export-path /results/`

**Comment by KingsleyLiu-NV** [comment]
Thanks a lot for your help. I think this issue can be closed. @dyastremsky
