### ISSUE TITLE
broken symlinks when using relative path for output_model_repository

### ISSUE THREAD

**Issue by user473** [triton-inference-server/model_analyzer#226]
When providing a relative path for `output_model_repository` the symlinks gets broken like in the following example:
with `output_model_repository_path: ./output-model-repository`  the model-analyzer generates the following directory structure,
```
output_model_repository/
├── encoder_i0
│   ├── 1 -> ./output_model_repository/encoder_i1/1
│   └── config.pbtxt
└── encoder_i1
    ├── 1
    │   └── model.py
    └── config.pbtxt
```
You can see from the symlink inside `encoder_i0`, it is pointing to `./output_model_repository/encoder_i1/1` which is `output_model_repository/encoder_i0/1/output_model_repository/encoder_i1/1` which doesn't exist and you get the following error
`2021-10-26 12:35:40.491 INFO[client.py:85] Model encoder_i0 load failed: load failed for model 'encoder_i0': failed to stat file ./output_model_repository/encoder_i0/1`

I believe we want the symlink to point to `../encoder_i1/1`

**Comment by Tabrizian** [comment]
@user473 Thanks for your contribution. Can you please sign the CLA and email it to triton-cla@nvidia.com?

https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by matthewkotila** [comment]
This bug has been fixed here and is merged into main 👍:

https://github.com/triton-inference-server/model_analyzer/pull/256
