### ISSUE TITLE
No such file or directory: 'tritonserver'

### ISSUE THREAD

**Issue by GuoGuiRong** [triton-inference-server/model_analyzer#243]
21.09 py  and 21.09 py-sdk docker image
when I use
```
root@VM-74-225-centos:/workspace#  model-analyzer profile  --profile-models TIS-recommend-onnx11 -m /data/home/guirongguo/ai/model_repository --override-output-model-repository
```
raise this error

**Comment by Tabrizian** [comment]
The SDK container does not tritonserver binary. If you want to use MA installed in the SDK container you need to use Docker mode. https://github.com/triton-inference-server/model_analyzer/blob/main/docs/launch_modes.md

You can also follow the quick start guide for a more easier introduction to MA:
https://github.com/triton-inference-server/model_analyzer/blob/main/docs/quick_start.md
