### ISSUE TITLE
when install model_analyzer raise Error

### ISSUE THREAD

**Issue by GuoGuiRong** [triton-inference-server/model_analyzer#244]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cheese/libcheese-gtk25_3.34.0-1ubuntu1_amd64.deb  502  Server UnReachable [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-docs/ubuntu-docs_20.04.3_all.deb  502  Server UnReachable [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-user-docs/gnome-user-docs_3.36.2+git20200704-0ubuntu0.1_all.deb  502  Server UnReachable [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-gl_1.16.2-4ubuntu0.1_amd64.deb  502  Server UnReachable [IP: 91.189.88.152 80]

I think this because install some InRelease sofeware. I use --fix-missing to ignore,but may occur some bug.

Can give a new version Docker to fix this problem?

**Comment by Tabrizian** [comment]
Not sure what you are trying to install here but the issue seems to be unrelated to Model Analyzer. Closing this issue.
