### ISSUE TITLE
How to use analyze with specific parameters? 

### ISSUE THREAD

**Issue by haritsahm** [triton-inference-server/model_analyzer#255]
I have a 18 configs sweep with a concurrency test from 1 - 40. Is there a way to analyze (or summarize) the model at a specific concurrency or test parameters? Right now if I want set an objective for lowest latency, it will recommend the result from concurrency of 1 (which is is the lowest) but it might be different at bigger concurrency .

**Comment by cvinson830** [comment]
Hi Muhammad, Thanks for logging this issue.  We will take a closer look next week.

**Comment by haritsahm** [comment]
Ah I see, thank you for the explanation. I will investigate this further.
