### ISSUE TITLE
Cant profile dynamic batch model

### ISSUE THREAD

**Issue by andreabrduque** [triton-inference-server/model_analyzer#270]
Hey guys

I have a model with the config.pbtxt below 

```
name: "ner"
platform: "onnxruntime_onnx"
max_batch_size: 100
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output [
  {
    name: "start_logits"
    data_type: TYPE_FP32
    dims: [ -1, 5 ]
  },
  {
    name: "end_logits"
    data_type: TYPE_FP32
    dims: [ -1, 5 ]
  }
]
```
and when I try to run model_analyzer, I get the following message:

```
2021-12-14 12:31:48.240 INFO[model_manager.py:224] Profiling model ner_i0...
2021-12-14 12:31:49.260 INFO[perf_analyzer.py:258] Running perf_analyzer ['perf_analyzer', '-m', 'ner_i0', '-b', '1', '-u', 'localhost:8001', '-i', 'grpc', '--concurrency-range', '1', '--measurement-mode', 'count_windows'] failed with exit status 1 : error: failed to create concurrency manager: input attention_mask contains dynamic shape, provide shapes to send along with the request
```

How can I config model_analyzer to send the shapes as well or its not possible to use it on dynamic batch model? Thank you

**Comment by Tabrizian** [comment]
When your model is using dynamic shapes, you need to specify the dimensions used in the `perf_analayzer_flags` section of Model Analyzer config https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#perf-analyzer-flags

For your model, it should look like below if you want to use 1 for the variable-sized shapes:

```yaml
perf_analyzer_flags:
  shape:
    - input_ids:1
    - token_type_ids:1
    - attention_mask:1
```

**Comment by matthewkotila** [comment]
The [config docs](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#perf-analyzer-flags) have been improved to make this more clear (https://github.com/triton-inference-server/model_analyzer/pull/271) 👍

**Comment by andreabrduque** [comment]
thank you, its working now.
