### ISSUE TITLE
Error when run model-analyzer in docker mode

### ISSUE THREAD

**Issue by ZJU-lishuang** [triton-inference-server/model_analyzer#344]
version : 21.11
install : Triton SDK Container
I'm trying to run model-analyzer in quick start but it is failing with the following error:
```
2022-03-12 04:48:52.559 ERROR[entrypoint.py:214] Model Analyzer encountered an error: Failed to set the value for field "triton_server_path". Error: Either the binary '/opt/tritonserver/' is not on the PATH, or Model Analyzer does not have permissions to execute os.stat on this path.
```

I have set the triton_server_path field to a binary file that exists . It did not work.
This is my command :
```
model-analyzer profile -m /workspace/model_analyzer/examples/quick-start/ --profile-models add_sub --triton-launch-mode=docker --output-model-repository=/home/outputmodel/output --triton-server-path=/opt/tritonserver/
```
I don't want to change the version. Can anyone help me ?

**Comment by tgerdesnv** [comment]
Note that this was fixed in newer versions. It sounds like you want to stay on 21.11 though.

It seems to be unhappy with the trailing backslash for triton-server-path.  This worked for me:

```
touch /opt/tritonserver
chmod +x /opt/tritonserver
model-analyzer profile -m /workspace/model_analyzer/examples/quick-start/ --profile-models add_sub --triton-launch-mode=docker --output-model-repository=/home/outputmodel/output --triton-server-path=/opt/tritonserver
```

**Comment by ZJU-lishuang** [comment]
It is useful.

**Comment by chintanckg** [comment]
> Note that this was fixed in newer versions. It sounds like you want to stay on 21.11 though.
> 
> It seems to be unhappy with the trailing backslash for triton-server-path. This worked for me:
> 
> ```
> touch /opt/tritonserver
> chmod +x /opt/tritonserver
> model-analyzer profile -m /workspace/model_analyzer/examples/quick-start/ --profile-models add_sub --triton-launch-mode=docker --output-model-repository=/home/outputmodel/output --triton-server-path=/opt/tritonserver
> ```

Issue still exists with the latest pull.
