### ISSUE TITLE
perf_analyzer: unrecognized option '--verbose-csv'

### ISSUE THREAD

**Issue by singhsobat** [triton-inference-server/model_analyzer#356]
Hey! I'm new to model analyzer.

I was following the quick start guide mentioned at https://github.com/triton-inference-server/model_analyzer/blob/main/docs/quick_start.md .

Upon profiling the sample model, the model-analyzer gives the following output:

` Profile complete. Profiled 0 configurations for models: []. `

When i try to have a look at the output above i see this error:
`INFO[perf_analyzer.py:264] Running perf_analyzer ['perf_analyzer', '-m', 'add_sub_config_8', '-b', '1', '-u', 'localhost:8001', '-i', 'grpc', '-f', 'add_sub_config_8', '--verbose-csv', '--concurrency-range', '1', '--measurement-mode', 'count_windows'] failed with exit status 1 : perf_analyzer: unrecognized option '--verbose-csv'`

**Comment by debermudez** [comment]
This looks to be an error coming from the underlying PA tool. Do you have an up to date version of PA as well?

**Comment by Tabrizian** [comment]
I think the issue is that you are following quick start guide on the `main` branch. Could you try following the quick start on `22.03` branch and clone the `22.03` branch of the Model Analyzer instead of the main branch? As indicated in the README, main branch is under-development:

> You are currently on the main branch which tracks under-development progress towards the next release. The latest release of the Triton Model Analyzer is 1.14.0 and is available on branch 22.03.

**Comment by singhsobat** [comment]
> I think the issue is that you are following quick start guide on the `main` branch. Could you try following the quick start on `22.03` branch and clone the `22.03` branch of the Model Analyzer instead of the main branch? As indicated in the README, main branch is under-development:
> 
> > You are currently on the main branch which tracks under-development progress towards the next release. The latest release of the Triton Model Analyzer is 1.14.0 and is available on branch 22.03.

I tried with the branch 22.03 but the same error pops up

**Comment by singhsobat** [comment]
> I think the issue is that you are following quick start guide on the `main` branch. Could you try following the quick start on `22.03` branch and clone the `22.03` branch of the Model Analyzer instead of the main branch? As indicated in the README, main branch is under-development:
> 
> > You are currently on the main branch which tracks under-development progress towards the next release. The latest release of the Triton Model Analyzer is 1.14.0 and is available on branch 22.03.

Thanks a lot! I cloned the r22.03 repository using the command `git clone -b r22.03 https://github.com/triton-inference-server/model_analyzer.git` and it worked fine!
