### ISSUE TITLE
is it possible to use model analyzer for triton-server 20.11?

### ISSUE THREAD

**Issue by ted8201** [triton-inference-server/model_analyzer#382]
Great work, just is it possible to analyse models for triton-server version 20.11? I have noticed the oldest branch is r20.12. I have ubuntu18, triton-server 20.12 is for ubuntu20. Anyway so this might work?

**Comment by tgerdesnv** [comment]
The versions are so old it is hard to say. You are welcome to try. If it doesn't work we won't be able to help or support you though.

**Comment by ted8201** [comment]
decouple model analyzer and triton-server

**Comment by ted8201** [comment]
thanks for the quick response!

**Comment by caoshuaibingcao** [comment]
I want to new model-analyzer in ubuntu18,but it only work in ubuntu20;why?

**Comment by caoshuaibingcao** [comment]
> 
如果ubuntu20的话把dockerfile下面这行注释就可以了。
#apt-get update && apt-get install -y --no-install-recommends software-properties-common &&

**Comment by Tabrizian** [comment]
The reason is that the libc version has changed in Ubuntu 20.04 and you cannot use the built perf analyzer in 18.04. You would need to build the perf analyzer yourself by following the instructions here:

https://github.com/triton-inference-server/client#build-using-cmake
