### ISSUE TITLE
System.ComponentModel.Win32Exception (2): No such file or directory

### ISSUE THREAD

**Issue by rotorliu** [triton-inference-server/model_analyzer#4]
Running the cmd on Linux threw this errors.

docker run -v /var/run/docker.sock:/var/run/docker.sock \
-v /ABSOLUTE/PATH/TO/MODELS:ABSOLUTE/PATH/TO/MODELS \
-v /ABSOLUTE/PATH/TO/EXPORT/DIRECTORY:/results --net=host \
nvcr.io/nvidia/clara/model-analyzer:ANALYZER-VERSION \
--batch BATCH-SIZES \
--concurrency CONCURRENCY-VALUES \
--model-names MODEL-NAMES \
--triton-version TRITON-VERSION \
--model-folder /ABSOLUTE/PATH/TO/MODELS \
--export --export-path /results/

**Comment by dyastremsky** [comment]
Hello! Can you provide your exact OS (i.e. which version of Linux)? In addition, please provide the command you are trying to run and full output.

Assuming you are able to [run Triton independently on your machine](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/run.html), this should be working. Note that the /ABSOLUTE/PATH/TO/MODELS should be the same in all three instances in the command (i.e. the absolute filepath should be the same in the host machine and container).

**Comment by rotorliu** [comment]
It's OK using .NET to build memory-analyzer.
