### ISSUE TITLE
Model Analyzer fails on Ensemble Model

### ISSUE THREAD

**Issue by klappec-bsci** [triton-inference-server/model_analyzer#400]
model-analyzer profile --model-repository models --profile-models myensemblemodel --run-config-search-max-concurrency 1 --run-config-search-max-model-batch-size 8 --run-config-search-max-instance-count 2

I get this error: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 559, in _ConvertFieldValuePair
    raise ParseError('Message type "{0}" should not have multiple '
google.protobuf.json_format.ParseError: Message type "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields at "ModelConfig".

During handling of the above exception, another exception occurred:

Is this a known issue with ensembles?  it works fine for each individual model in the ensemble.

**Comment by tgerdesnv** [comment]
Unfortunately Model Analyzer does not yet work with ensembles. It is on the roadmap

**Comment by klappec-bsci** [comment]
@tgerdesnv 

does perf-analyzer work with ensembles? so far it doesnt seem to, I get errors that the input data wasn't specified and the thread failed.

**Comment by tgerdesnv** [comment]
Hi @klappec-bsci, Perf Analyzer does work with ensembles.  Please open a separate issue in https://github.com/triton-inference-server/server with more details (command you ran, error log, etc).

**Comment by NikeNano** [comment]
For med `pref_analyzer` works fine for ensembles.

**Comment by vinayak-shanawad** [comment]
Hi @tgerdesnv 

Model analyzer does not seems to be working in 22.08 release due to following error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/json_format.py", line 530, in _ConvertFieldValuePair
    raise ParseError('Message type "{0}" should not have multiple '
google.protobuf.json_format.ParseError: Message type "inference.ModelConfig" should not have multiple "scheduling_choice" oneof fields.

Not able to build 22.09 triton server docker due to following error.
manifest for nvcr.io/nvidia/tritonserver:22.09-py3-sdk not found: manifest unknown: manifest unknown

Any updates please?

Thanks

**Comment by tgerdesnv** [comment]
1)
ensembles are not yet supported in Model Analyzer. We are getting much closer, but it is still a few releases away.


>manifest for nvcr.io/nvidia/tritonserver:22.09-py3-sdk not found: manifest unknown: manifest unknown

22.09 has not been released yet. It has been delayed, but is planned to be released early this week


2)
It sounds like you are confusing perf analyzer's batch size with the model's max batch size.
Perf Analyzer's batch size is the number of requests in each message sent to triton.
The model's max batch size is the number of requests it can batch together and send to the inference compute engine.
Perf Analyzer can help gather datapoints to compare model configurations, but it can't change the model configuration for you.  That is where model analyzer is normally used -- creating, profiling, and comparing model configurations to find the best one.

**Comment by ychuang970303** [comment]
hi，@tgerdesnv
    I'm trying to use model-analyzer on the bls models, but also get some errors, I'm wondering does model-analyzer support bls models now?
Thanks

**Comment by tgerdesnv** [comment]
@ychuang970303 unfortunately bls models are not supported yet. They are still on our roadmap and will be coming soon

**Comment by tgerdesnv** [comment]
@ychuang970303 @klappec-bsci note that ensemble support will be in the 23.02 release, which comes out in a few days. BLS will not be included in that release, but should come out in one of the next few releases after.

**Comment by NikeNano** [comment]
> @ychuang970303 @klappec-bsci note that ensemble support will be in the 23.02 release, which comes out in a few days. BLS will not be included in that release, but should come out in one of the next few releases after.

Awsome, really excited for this

**Comment by nv-braf** [comment]
23.02 has been released. Ensemble support is now available in MA
