### ISSUE TITLE
Quickstart : Unable to run the model-analyzer docker container locally

### ISSUE THREAD

**Issue by aishanibhalla** [triton-inference-server/model_analyzer#409]
I followed the [quickstart](https://github.com/triton-inference-server/model_analyzer/blob/r22.04/docs/quick_start.md) to create the model analyzer container locally. 

Issue 1:  Got the following error in the build step:
```#23 474.3 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/d/dbus/dbus-x11_1.12.16-2ubuntu2.1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
#23 474.3 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
#23 474.3 Fetched 206 MB in 7min 51s (436 kB/s)
------
executor failed running [/bin/sh -c apt-get install -y wkhtmltopdf]: exit code: 100
```

I added `RUN apt-get update --fix-missing` as suggested.

The image got built after 933.2s 

Issue 2: docker run command:

```
docker run -it --rm --gpus all `
>> -v ${pwd}/examples/quick-start:/quick_start_repository `
>> --net=host --name model-analyzer `
>> model-analyzer /bin/bash
```

gives me the following error:

```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: load library failed: /usr/lib/wsl/drivers/iigd_dch_jaz.inf_amd64_00e3a91e23dede75/libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
```

Please suggest; I'm using the `r22.04` branch for development on Windows, Docker Engine `v20.10.14`

**Comment by tgerdesnv** [comment]
For issue #2, the quick start is designed for basic linux use. Triton Server does have a beta release of Windows in 22.04, but Perf Analyzer (and thus Model Analyzer) does not support windows. You could still create a windows Triton Server and then use Model Analyzer in remote mode from Linux, but its behavior would be limited.
