### ISSUE TITLE
How are the results sorted?

### ISSUE THREAD

**Issue by Kokkini** [triton-inference-server/model_analyzer#435]
When the model_analyzer picks the 3 best model configs it uses the perf_throughput objective to compare by default. However, each config has multiple throughput values at multiple concurrency levels. How does the model_analyzer aggregate these multiple values to get a single value? Does it average the throughput values at different concurrency levels or simply take the max throughput values?

**Comment by tgerdesnv** [comment]
Hi Quang,
You are correct that by default ModelAnalyzer will sort by throughput.  When it does that, it will take the highest throughput of each config when comparing configs.
