### ISSUE TITLE
Unable to fetch pre-built model_analyzer docker container

### ISSUE THREAD

**Issue by yasirofficial** [triton-inference-server/model_analyzer#5]
It's mentioned [here](https://developer.nvidia.com/blog/maximizing-deep-learning-inference-performance-with-nvidia-model-analyzer/) that we can pull a pre-built container using docker pull **nvcr.io/nvidia/clara/model-analyzer:latest** command. However, this command always fail with a message _"Error response from daemon: unauthorized: authentication required"_ I've tried finding the container [here](https://ngc.nvidia.com/catalog/containers) and it doesn't seems to appear.

**Comment by dyastremsky** [comment]
Model Analyzer was set to go live this month with one of the Clara Deploy releases, which the article originally stated. However, once it was made open source, the article was updated to reflect that, as you can now build it via the quickstart instructions in the repo. @igobypenn or @whoisj can speak better to when it will be deployed to NGC, if at all (if not, it may make sense to update the article).

**Comment by whoisj** [comment]
@yasirofficial something happened, and I'm not quite sure what; but you're correct the model-analyzer container did not publish correctly. I've been out on vacation for the past couple of week, and I'm just getting caught up with things. I'll look into this issue asap.

Thanks @dyastremsky for highlighting this issue.

**Comment by whoisj** [comment]
This issue should have been resolved on the docker image host side of things. Thanks for bringing it to our attention.
