### ISSUE TITLE
Model analyzer is able to create the new configs but perf_analyzer is failing.

### ISSUE THREAD

**Issue by vaishnavi-kotturu** [triton-inference-server/model_analyzer#563]
**Command used inside model_analyzer container:**
```model-analyzer profile --model-repository /model_repository --profile-models trno_estimator --override-output-model-repository```

**LOGS:**

[Model Analyzer] Creating model config: trno_estimator_config_4
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer]   Setting instance_group to [{'count': 5, 'kind': 'KIND_CPU'}]
[Model Analyzer] 
[Model Analyzer] Profiling trno_estimator_config_4: client batch size=1, concurrency=1
[Model Analyzer] CPU metric(s) are not being collected, while this profiling will run on CPU(s).
[Model Analyzer] Running perf_analyzer failed with exit status 1 : error: failed to create concurrency manager: input input contains dynamic shape, provide shapes to send along with the request

**Here's my config.pbtxt:**

********************************************************************
name: "trno_estimator"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [-1,3,-1,-1]
    reshape { shape: [ -1,3,-1,-1 ] }
  }
]

output [
    {
    name: "output"
    data_type: TYPE_FP32
    dims: [-1, 2]
  }
]

instance_group [{
      count: 1
      kind: KIND_CPU
    }]

dynamic_batching { }

********************************************************************

How to run model_analyzer for models with dynamic shape?

**Comment by tgerdesnv** [comment]
> How to run model_analyzer for models with dynamic shape?

Perf Analyzer needs to know the shape(s) of data to send. For models that use variable/dynamic dimensions, this data needs to be provided.  You can supply it in the perf_analyzer_flags section of a config.yml file passed to Model Analyzer. More details here:
https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#shape-input-data-and-streaming

**Comment by vaishnavi-kotturu** [comment]
> > How to run model_analyzer for models with dynamic shape?
> 
> Perf Analyzer needs to know the shape(s) of data to send. For models that use variable/dynamic dimensions, this data needs to be provided. You can supply it in the perf_analyzer_flags section of a config.yml file passed to Model Analyzer. More details here: https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#shape-input-data-and-streaming

Could you give a sample command to run? Because i don't have any config.yml created already.

**Comment by tgerdesnv** [comment]
config.yml:
```
perf_analyzer_flags:
  shape:
    - input:1,3,1,1
```

model-analyzer profile **-f config.yml** --model-repository /model_repository --profile-models trno_estimator --override-output-model-repository

**Comment by vaishnavi-kotturu** [comment]
Understood, thanks for the help. Closing the issue
