### ISSUE TITLE
use s3 repository for model configs when using remote triton

### ISSUE THREAD

**Issue by Rusteam** [triton-inference-server/model_analyzer#584]
Hi there,

**Problem**

When launching the analyzer in the remote mode (`--triton-launch-mode=remote`), it's not possible to test various model configs because the remote Triton is unable to read model configs from the same host path. 

**Solution**

Triton inference server supports reading models from an S3 storage and we could use that to run model-analyzer with a remote Triton and write model configs to a S3 storage (something like `--output-model-repository-path=s3://mybucket/triton-model-repository`). 

I'm willing to contribute with this PR if approved for development.

**Comment by tgerdesnv** [comment]
Hi @Rusteam 

You are correct that Model Analyzer does not currently support sweeping configs in remote mode. The issue isn't just finding storage that both MA and the server have access to. MA also needs the ability to load and unload models on a remote server.

It is on our roadmap to support remote sweeping of configs.  The solution is likely to load and unload via the client API,  so I don't believe it would require something like S3 repository.

**Comment by Rusteam** [comment]
That's cool too. If you want help, let me know
