### ISSUE TITLE
client interface when running model_analyzer

### ISSUE THREAD

**Issue by BobDLA** [triton-inference-server/model_analyzer#611]
I have seraval question about the interface setting for model_analyzer.
* Which client inferface is using when runing model_analyzer?
   Is that grpc or http interface? Is the shm enable?  
* Does the metric count the time transfer data between client and server?
* Is these setting  configureable?

Thanks

**Comment by tgerdesnv** [comment]
Full information about configuration Model Analyzer can be found [here](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md)

> Which client inferface is using when runing model_analyzer? Is that grpc or http interface?

This option is available on via the CLI or via a yaml config passed to model analyzer:
```
# The protocol used to communicate with the Triton Inference Server. Only 'http' and 'grpc' are allowed for the values.
[ client_protocol: <string> | default: grpc ]
```


>Is the shm enable?

By default, no. Under the hood model_analyzer uses [Perf Analyzer](https://github.com/triton-inference-server/client/tree/main/src/c%2B%2B/perf_analyzer). We are actively working on the docs for that tool. It has a [shared memory](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/command_line_parser.cc#L405-L408) option.

Perf analyzer flags can be specified to Model Analyzer via the following model_analyzer option in the **yaml config**:

```
# Allows custom configuration of perf analyzer instances used by model analyzer
[ perf_analyzer_flags: <dict> ]
```

Here is an example yaml config that uses http and CUDA shared memory when using local mode
```
client_protocol: http
perf_analyzer_flags:
        shared-memory: system
```

Launched like this:
`model-analyzer profile -m <model repo> --profile-models <model> -f config.yaml `

> Does the metric count the time transfer data between client and server?

Yes, that is part of the reported latency

> Is these setting configureable?

The answer is yes to everything except for ignoring data transfer time

**Comment by BobDLA** [comment]
> Full information about configuration Model Analyzer can be found [here](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md)
> 
> > Which client inferface is using when runing model_analyzer? Is that grpc or http interface?
> 
> This option is available on via the CLI or via a yaml config passed to model analyzer:
> 
> ```
> # The protocol used to communicate with the Triton Inference Server. Only 'http' and 'grpc' are allowed for the values.
> [ client_protocol: <string> | default: grpc ]
> ```
> 
> > Is the shm enable?
> 
> By default, no. Under the hood model_analyzer uses [Perf Analyzer](https://github.com/triton-inference-server/client/tree/main/src/c%2B%2B/perf_analyzer). We are actively working on the docs for that tool. It has a [shared memory](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/command_line_parser.cc#L405-L408) option.
> 
> Perf analyzer flags can be specified to Model Analyzer via the following model_analyzer option in the **yaml config**:
> 
> ```
> # Allows custom configuration of perf analyzer instances used by model analyzer
> [ perf_analyzer_flags: <dict> ]
> ```
> 
> Here is an example yaml config that uses http and CUDA shared memory when using local mode
> 
> ```
> client_protocol: http
> perf_analyzer_flags:
>         shared-memory: system
> ```
> 
> Launched like this: `model-analyzer profile -m <model repo> --profile-models <model> -f config.yaml `
> 
> > Does the metric count the time transfer data between client and server?
> 
> Yes, that is part of the reported latency
> 
> > Is these setting configureable?
> 
> The answer is yes to everything except for ignoring data transfer time

Thank you for the very detail answer.
