### ISSUE TITLE
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: No checkpoint file found

### ISSUE THREAD

**Issue by JasonChao-yue** [triton-inference-server/model_analyzer#638]
I use the command below to create docker
docker run -it --gpus all -v /var/run/docker.sock:/var/run/docker.sock -v /home/Documents/analyzerceshi1/resp/model_analyzer-r22.06/examples/quick-start:	  -v /home/Documents/analyzerceshi1/path-to-output-model-repo:/path-to-output-model-repo --net=host nvcr.io/nvidia/tritonserver:22.06-py3-sdk

root@nvidia-B360M-D2V:/workspace/analyzer# model-analyzer analyze --analysis-models add_sub -e analysis_results
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 411, in main
    analyzer = Analyzer(config,
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 61, in __init__
    state_manager.load_checkpoint(checkpoint_required)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/state/analyzer_state_manager.py", line 138, in load_checkpoint
    raise TritonModelAnalyzerException(f'No checkpoint file found')
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: No checkpoint file found
root@nvidia-B360M-D2V:/workspace/analyzer#

**Comment by nv-braf** [comment]
Have you profiled the model first? Analysis is only done on a previously profiled model (which creates a checkpoint).

**Comment by JasonChao-yue** [comment]
> Have you profiled the model first? Analysis is only done on a previously profiled model (which creates a checkpoint).

resolved ! thank you
