### ISSUE TITLE
Multi model detailed report generation error

### ISSUE THREAD

**Issue by jmuppave** [triton-inference-server/model_analyzer#658]
I just tried the suggested report command at the end of profile. But was facing this error:

`model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: RunConfig xyz_config_default requested for report step but no results were found.`

Using tritonserver:23.02-py3-sdk.

**Comment by nv-braf** [comment]
Detailed report generation is not supported for multi-model runs. An error message should be printed if it is attempted and no suggested report command should be given if profiling is done with the `--run-config-profile-models-concurrently-enable` option.

@jmuppave Can you please share the exact command line/configuration details about the profile and report commands you ran.

**Comment by jmuppave** [comment]
_Profile command:_  `model-analyzer profile -f config.yaml`
_Report command_: (suggested)
`model-analyzer report --report-model-configs xyz_config_default,xyz_best_config_default,xyz_fp16_config_1 --export-path /model_analyzer_output/exports --config-file config.yaml --checkpoint-directory /model_analyzer_output/checkpoints`

**Comment by nv-braf** [comment]
I'll need more info. Can you share the contents of your config.yaml? Can you also confirm that the profile was successful (measurements were taken and a checkpoint was created)? 
Also, it looks like this isn't a multi-model run, but several different single models run sequentially (xyz, xyz_fp16)? Can you confirm that is your intent?

**Comment by jmuppave** [comment]
Here is my config:

`model_repository: /model_repo
checkpoint_directory: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/checkpoints
output_model_repository_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/configs
override_output_model_repository: true
triton_output_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/ma.log
export_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/exports

triton_launch_mode: docker
triton_docker_image: nvcr.io/nvidia/tritonserver:22.07-py3
run_config_search_mode: quick


run_config_profile_models_concurrently_enable: true
profile_models:
  - xyz_fp16
  - xyz_best
  - xyz_int8_calib

collect_cpu_metrics: true
perf_output: true
perf_output_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/ma_pa.log`

Yes, Profile was successful. I even got summary reports. Only for detailed report generation I got the error.

**Comment by jmuppave** [comment]
> Like I stated earlier, detailed reporting is not supported for multi-model runs (this is indicated in our documentation).
> 
> And, in the more recent versions 23.02+ we no longer print out a message about running detailed reporting and will also throw an error if it is attempted (which is why I asked you for more info).
> 
> Looks like you are running on 22.07-py3 which is why you still got the detailed report instructions, but even then our documentation indicates that this is not supported.
> 
> Is there something specific that summary report isn't providing you that you are looking for in a detailed report?

No, I thought you wanted to know the details to understand the error.
