### ISSUE TITLE
Error loading LD_PRELOAD custom.so and libtritonserver.so

### ISSUE THREAD

**Issue by jmuppave** [triton-inference-server/model_analyzer#659]
I am trying to load custom .so using:

`'triton_server_environment': {
            'LD_PRELOAD': '/model_repo/xyz/1/libtriton_xyz_nn_parser.so'
            },`

whenever I do this I am facing following errors:

- In triton logs: `ERROR: ld.so: object '/model_repo/xyz/1/libtriton_xyz_nn_parser.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
- In model-analyzer terminal: `[Model Analyzer] Running perf_analyzer failed with exit status 127:
perf_analyzer: error while loading shared libraries: libtritonserver.so: cannot open shared object file: No such file or directory
`

I have checked and confirmed `'/model_repo/xyz/1/libtriton_xyz_nn_parser.so'` exists in the model directory. I have compiled this .so on tritonserver:22.07 and using same triton version in model analyzer.

Any idea why this is happening?

**Comment by nv-braf** [comment]
Not enough information for me to tell why it's not being loaded. Are you running inside a container? Are you running in local or docker mode? 

If you would like additional help please share your the command line you ran along with any configuration files.

**Comment by jmuppave** [comment]
I am running it with in nvcr.io/nvidia/tritonserver:23.02-py3-sdk (model_analyzer) container and using docker mode.

model analyzer config:

```
model_repository: /model_repo
checkpoint_directory: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/checkpoints
output_model_repository_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/configs
override_output_model_repository: true
triton_output_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/ma.log
export_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/exports

triton_launch_mode: docker
triton_docker_image: nvcr.io/nvidia/tritonserver:22.07-py3
run_config_search_mode: quick


profile_models: ensemble_xyz_int8_calib

triton_server_environment:
  LD_PRELOAD: /model_repo/xyz_postprocess/1/libtriton_custom_nn_parser.so

collect_cpu_metrics: true
perf_output: true
perf_output_path: /model_analyzer_output/xyz_ma_test/ensemble_xyz_int8_calib/ma_pa.log
```

command: `model-analyzer profile -f ma_config.yaml`

All the triton models are mapped to `/model_repo` in model_analyzer container.

The plan files of triton models are generated using a separate tritonserver:22.07 container, similar case with libtriton_custom_nn_parser.so.

Does compiling libtriton_custom_nn_parser.so file in a particular container link to its specific libtritonserver.so? If so how to reuse libtriton_custom_nn_parser.so in model_analyzer?

**Comment by nv-braf** [comment]
Have you ensured that all paths are absolute and are identical on both sides of the symbolic links when creating the container?

**Comment by jmuppave** [comment]
I removed the LD_PRELOAD environment from config and it's working fine.

In older version I had to use LD_PRELOAD, I think it's not needed anymore.
