### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by SafrMSD** [triton-inference-server/model_analyzer#668]
I created and connected 3 directories
model_out:/model_out
profile_results:/profile_results
model_repository:/models
The add_sub model is located in the model_repository directory

docker run -it --rm --gpus all -v //var/run/docker.sock:/var/run/docker.sock -v D:/triton-inference-server/model_repository:/models -v D:/triton-inference-server/model_analyzer/model_out:/model_out -v D:/triton-inference-server/model_analyzer/profile_results:/profile_results --net=host nvcr.io/nvidia/tritonserver:23.03-py3-sdk

then I run the analysis

model-analyzer profile --model-repository /models --profile-models add_sub --triton-launch-mode=docker --output-model-repository-path /model_out/out --export-path /profile_results --run-config-search-max-concurrency 2 --run-config-search-max-model-batch-size 2 --run-config-search-max-instance-count 2 --override-output-model-repository

[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 NVIDIA GeForce RTX 2070 with UUID GPU-7e946a10-0fdc-a67e-6007-87ab98cf2333
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
[Model Analyzer]
[Model Analyzer] Creating model config: add_sub_config_default
[Model Analyzer]
[Model Analyzer] Model add_sub_config_default load failed: [StatusCode.INTERNAL] failed to load 'add_sub_config_default', failed to poll from model repository
[Model Analyzer]
[Model Analyzer] Creating model config: add_sub_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer]
[Model Analyzer] Model add_sub_config_0 load failed: [StatusCode.INTERNAL] failed to load 'add_sub_config_0', failed to poll from model repository
[Model Analyzer]
[Model Analyzer] Creating model config: add_sub_config_1
[Model Analyzer]   Setting instance_group to [{'count': 2, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer]
[Model Analyzer] Model add_sub_config_1 load failed: [StatusCode.INTERNAL] failed to load 'add_sub_config_1', failed to poll from model repository
[Model Analyzer] Saved checkpoint to /workspace/checkpoints/0.ckpt
[Model Analyzer] Profile complete. Profiled 0 configurations for models: []
[Model Analyzer]
[Model Analyzer] WARNING: Inference output field "perf_throughput", has no data
[Model Analyzer] WARNING: Inference output field "perf_latency_p99", has no data
[Model Analyzer] Exporting server only metrics to /profile_results/results/metrics-server-only.csv
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] WARNING: No data found for model add_sub, skipping export summary.
[Model Analyzer] WARNING: Requested top 3 configs, but none satisfied constraints. Showing available constraint failing configs for this model.
[Model Analyzer] WARNING: Requested top 3 configs, but found only 0. Showing all available configs for this model.
[Model Analyzer] To generate detailed reports for the 0 best add_sub configurations, run `model-analyzer report --report-model-configs  --export-path /profile_results`

**Comment by tgerdesnv** [comment]
See the bullet at the end of [step 2](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/quick_start.md#step-2-pull-and-run-the-sdk-container):

`Important: You must ensure the absolutes paths are identical on both sides of the mounts (or else Tritonserver cannot load the model)`

So, instead of linking in like this: `-v D:/triton-inference-server/model_analyzer/model_out:/model_out`
You need to link in directories with the full path like this: `-v D:/triton-inference-server/model_analyzer/model_out:/triton-inference-server/model_analyzer/model_out`

**Comment by SafrMSD** [comment]
I was able to resolve the issue
it was not obvious to me that the output model directory should not exist on the host

Here is a similar question

https://github.com/triton-inference-server/model_analyzer/issues/120

Here is an example of a correct docker command

docker run -it --rm --gpus all -v //var/run/docker.sock:/var/run/docker.sock -v D:/triton-inference-server/model_repository:/models -v /model_out:/model_out -v D:/triton-inference-server/model_analyzer/profile_results:/profile_results --net=host nvcr.io/nvidia/tritonserver:23.03-py3-sdk
