### ISSUE TITLE
how to provide custom input data while run profile subcommand

### ISSUE THREAD

**Issue by DequanZhu** [triton-inference-server/model_analyzer#680]
I have a ensemble model accept bytes like image input data which shapes [-1] in triton config file,  then  decode it to matrix like image data for next cnn trt model. Now I want to use model_profile tool to find the best configuration for this ensemble model. I must provide real image input data for the decode image module, because random generated input data can't be decoded by decode module. How can I provided this input data for the profile subcommand?

**Comment by tgerdesnv** [comment]
Here you can learn about the different options for passing in input data into Perf_Analyzer:
https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/input_data.md

Model Analyzer uses Perf_Analyzer under the hood. This shows how to specify Perf Analyzer flags into MA:
https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#perf-analyzer-flags

**Comment by DequanZhu** [comment]
@tgerdesnv thanks so much, it works for me
