### ISSUE TITLE
Model analyzer process hangs and never terminates

### ISSUE THREAD

**Issue by wemoveon2** [triton-inference-server/model_analyzer#686]
Hi, I'm trying to integrate Huggingface Accelerate V0.14 into my existing Kubeflow pipeline which utilizes `model-analyzer` as part of the benchmark step. While the model seems to load correctly, the pipeline freezes and hangs because the `model-analyzer` process never seems to finish. From `ps xao`, I can see that `model-analyzer` calls `tritonserver` which calls `trito`, but the `trito` process is defunct. Any help with further debugging this issue would be highly appreciated.

```
# ps axao pid,ppid,pgid,comm,sid
  PID  PPID  PGID COMMAND           SID
    1     0     1 argoexec            1
   33     1    33 python3             1
  131     1    33 pytho <defunct>     1
  132     1    33 pytho <defunct>     1
  133     1    33 pytho <defunct>     1
  645    33    33 model-analyzer      1
  876   645   876 tritonserver      876
 1102   876   876 trito <defunct>   876
 1358     0  1358 bash             1358
 1615  1358  1615 ps               1358
```

**Comment by tgerdesnv** [comment]
Does it hang at the start (model analyzer does nothing), or at the end (model analyzer finishes profiling but hangs)?

Are you able to successfully run without Model Analyzer?

**Comment by wemoveon2** [comment]
@tgerdesnv I believe it's at the start when `model-analyzer` tries to start `tritonserver` but fails or the process takes too long.

I _think_  I may have found a fix, although I'm no longer testing the integration as there were many other weird bugs that came up when I tried integrating `accelerate`. 

I don't think the `tritonserver` command actually failed since I'd see that failure in my KFP logs, instead, I think there's some weird interaction when loading a big model into the CPU with disk offloading. For whatever reason, when using `accelerate`, one must export the visible devices explicitly before importing any of the HuggingFace libraries by calling `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`. I don't know why this is the case since `torch` in the same environment can already see the available GPUs. 

I'll keep this issue open for a few more days if you don't mind. We're still looking to integrate `accelerate` sometime in the future and I personally would love some clarity on this issue.
