### ISSUE TITLE
How to send sequece data while using perf-analyzer ?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/model_analyzer#737]
In python client, i am able to send a sequence image data like: 
```
result = self.triton_client.infer(self.model_name,
                                          inputs=inputs,
                                          request_id=real_request_id,
                                          sequence_id = self.camera_id,
                                          sequence_start=start_frame,
                                          sequence_end=stop_frame,
                                          outputs=outputs)
```
I want to use perf-analyzer to do analysis, but i do not know how to prepare the input data, and there exists no clear tutorial.

**Comment by matthewkotila** [comment]
Hi @monsterlyg, sorry that it hasn't been clear. Have you checked out the input data documentation?:

https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/input_data.md#real-input-data

> Perf Analyzer will use the provided data in a round-robin order when sending inference requests. For sequence models, if a sequence length is specified via [--sequence-length](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/cli.md#--sequence-lengthn), Perf Analyzer will also loop through the provided data in a round-robin order up to the specified sequence length (with a percentage variation customizable via [--sequence-length-variation](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/cli.md#--sequence-length-variationn)). Otherwise, the sequence length will be the number of inputs specified in user-provided input data.

Take, for example, the PA command:

```
perf_analyzer -m my_sequence_model --num-sequences=1 --input-data=input_data.json
```

And take, for example, the provided `input_data.json`:
```
{
    "data":
      [
        {
          "INPUT": [1],
        },
        {
          "INPUT": [3],
        },
        {
          "INPUT": [5],
        }
      ]
  }
```

Perf Analyzer will set the sequence length to 3 since there are 3 inputs provided. Perf Analyzer will send the first request of the only active sequence of `my_sequence_model` with `1` as the value for input `INPUT`. Then the second request to the same sequence will have `3` as the value for input `INPUT`. Then the third request will have `5` as the value for input `INPUT`.

Let me know if it's still unclear and if your use case is different from this and I'll try to get an example for you.

**Comment by monsterlyg** [comment]
Thanks for explanation. I have figured it out hours ago.



---Original---
From: "Matthew ***@***.***&gt;
Date: Wed, Aug 2, 2023 23:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [triton-inference-server/model_analyzer] How to send sequece datawhile using perf-analyzer ? (Issue #737)




 
Hi @monsterlyg, sorry that it hasn't been clear. Have you checked out the input data documentation?:
 
https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/input_data.md#real-input-data
  
Perf Analyzer will use the provided data in a round-robin order when sending inference requests. For sequence models, if a sequence length is specified via --sequence-length, Perf Analyzer will also loop through the provided data in a round-robin order up to the specified sequence length (with a percentage variation customizable via --sequence-length-variation). Otherwise, the sequence length will be the number of inputs specified in user-provided input data.
  
Take, for example, the PA command:
 perf_analyzer -m my_sequence_model --num-sequences=1 --input-data=input_data.json  
And take, for example, the provided input_data.json:
 {     "data":       [         {           "INPUT": [1],         },         {           "INPUT": [3],         },         {           "INPUT": [5],         }       ]   }  
Perf Analyzer will set the sequence length to 3 since there are 3 inputs provided. Perf Analyzer will send the first request of the only active sequence of my_sequence_model with 1 as the value for input INPUT. Then the second request to the same sequence will have 3 as the value for input INPUT. Then the third request will have 5 as the value for input INPUT.
 
Let me know if it's still unclear and if your use case is different from this and I'll try to get an example for you.

**Comment by fighterhit** [comment]
Hi @matthewkotila , I have a sequence model, but it only has one input type of TYPE_STRING, which is binary data packaged with MessagePack and relies on real data. Does perf_analyze support this? I see that perf_analyze supports custom input in json files, but json files may not support binary data, right?

**Comment by matthewkotila** [comment]
Yes you can use binary data. Look for "b64" in the above linked documentation.

**Comment by fighterhit** [comment]
> Yes you can use binary data. Look for "Base64" in the documentation:是的，您可以使用二进制数据。在文档中查找“Base64”：
> 
> [https://github.com/triton-inference-server/perf_analyzer/blob/main/docs/input_data.md#real-input-datahttps://github.com/triton-inference-server/perf_analyzer/blob/main/docs/input_data.md#real-input-data](https://github.com/triton-inference-server/perf_analyzer/blob/main/docs/input_data.md#real-input-data)

Thanks @matthewkotila , does `model_analyzer` support custom input for BLS stateful model? I don't seem to see any relevant parameters for profiles.
```
usage: model-analyzer profile [-h] [-f CONFIG_FILE] [-s CHECKPOINT_DIRECTORY] [-i MONITORING_INTERVAL] [-d DURATION_SECONDS] [--collect-cpu-metrics] [--gpus GPUS] [--always-report-gpu-metrics]
                              [--skip-summary-reports] [--skip-detailed-reports] [--model-type MODEL_TYPE] [-m MODEL_REPOSITORY] [--output-model-repository-path OUTPUT_MODEL_REPOSITORY_PATH]
                              [--override-output-model-repository] [-r CLIENT_MAX_RETRIES] [--client-protocol {http,grpc}] [--profile-models PROFILE_MODELS] [-b BATCH_SIZES] [-c CONCURRENCY]
                              [--request-rate REQUEST_RATE] [--reload-model-disable] [--bls-composing-models BLS_COMPOSING_MODELS] [--cpu-only-composing-models CPU_ONLY_COMPOSING_MODELS]
                              [--perf-analyzer-timeout PERF_ANALYZER_TIMEOUT] [--perf-analyzer-cpu-util PERF_ANALYZER_CPU_UTIL] [--perf-analyzer-path PERF_ANALYZER_PATH] [--perf-output]
                              [--perf-output-path PERF_OUTPUT_PATH] [--perf-analyzer-max-auto-adjusts PERF_ANALYZER_MAX_AUTO_ADJUSTS] [--triton-launch-mode {local,docker,remote,c_api}]
                              [--triton-docker-image TRITON_DOCKER_IMAGE] [--triton-http-endpoint TRITON_HTTP_ENDPOINT] [--triton-grpc-endpoint TRITON_GRPC_ENDPOINT]
                              [--triton-metrics-url TRITON_METRICS_URL] [--triton-server-path TRITON_SERVER_PATH] [--triton-output-path TRITON_OUTPUT_PATH]
                              [--triton-docker-mounts TRITON_DOCKER_MOUNTS] [--triton-docker-shm-size TRITON_DOCKER_SHM_SIZE] [--triton-install-path TRITON_INSTALL_PATH] [--early-exit-enable]
                              [--run-config-search-max-concurrency RUN_CONFIG_SEARCH_MAX_CONCURRENCY] [--run-config-search-min-concurrency RUN_CONFIG_SEARCH_MIN_CONCURRENCY]
                              [--run-config-search-max-request-rate RUN_CONFIG_SEARCH_MAX_REQUEST_RATE] [--run-config-search-min-request-rate RUN_CONFIG_SEARCH_MIN_REQUEST_RATE]
                              [--run-config-search-max-instance-count RUN_CONFIG_SEARCH_MAX_INSTANCE_COUNT] [--run-config-search-min-instance-count RUN_CONFIG_SEARCH_MIN_INSTANCE_COUNT]
                              [--run-config-search-max-model-batch-size RUN_CONFIG_SEARCH_MAX_MODEL_BATCH_SIZE] [--run-config-search-min-model-batch-size RUN_CONFIG_SEARCH_MIN_MODEL_BATCH_SIZE]
                              [--run-config-search-max-binary-search-steps RUN_CONFIG_SEARCH_MAX_BINARY_SEARCH_STEPS] [--min-percentage-of-search-space MIN_PERCENTAGE_OF_SEARCH_SPACE]
                              [--max-percentage-of-search-space MAX_PERCENTAGE_OF_SEARCH_SPACE] [--optuna-min-trials OPTUNA_MIN_TRIALS] [--optuna-max-trials OPTUNA_MAX_TRIALS]
                              [--optuna-early-exit-threshold OPTUNA_EARLY_EXIT_THRESHOLD] [--use-concurrency-formula] [--run-config-search-mode {brute,quick,optuna}]
                              [--run-config-search-disable] [--run-config-profile-models-concurrently-enable] [--request-rate-search-enable] [--concurrency-sweep-disable] [-e EXPORT_PATH]
                              [--filename-model-inference FILENAME_MODEL_INFERENCE] [--filename-model-gpu FILENAME_MODEL_GPU] [--filename-server-only FILENAME_SERVER_ONLY]
                              [--num-configs-per-model NUM_CONFIGS_PER_MODEL] [--num-top-model-configs NUM_TOP_MODEL_CONFIGS] [--inference-output-fields INFERENCE_OUTPUT_FIELDS]
                              [--gpu-output-fields GPU_OUTPUT_FIELDS] [--server-output-fields SERVER_OUTPUT_FIELDS] [--latency-budget LATENCY_BUDGET] [--min-throughput MIN_THROUGHPUT]
```
