### ISSUE TITLE
Run models concurrently

### ISSUE THREAD

**Issue by naveengogineni** [triton-inference-server/model_analyzer#74]
We know that the below command (with -n flag) benchmark the models in sequence -
model-analyzer -m /models/ -n model1, model2  --batch-sizes 1,2,4,8,16 -c 1,2,3

My requirement is to benchmark multiple models concurrently on a single GPU and was exploring to find out if there is a flag where we could pass models as arguments and the model analyzer could run them concurrently instead of running them in sequence?

**Comment by Tabrizian** [comment]
Thanks for your feature request. This is on our roadmap for this project. We'll update this issue whenever this feature is available.

**Comment by ydzhang12345** [comment]
would love to have this feature too

**Comment by jishminor** [comment]
Are there any updates for the timeline of the completion of this feature?

**Comment by matthewkotila** [comment]
The feature is on our roadmap, but we do not have an ETA at this time.

**Comment by tgerdesnv** [comment]
This won't be in 22.04, but at least an early access version should be available in the next few releases

**Comment by tgerdesnv** [comment]
FYI This feature is now available:
https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config_search.md#multi-model-search-mode
