### ISSUE TITLE
Different perf_analyzer results?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/model_analyzer#740]
I've obeserved a strange phenomenon that the 'throughput' in MA result report is different from the one measured directly by PA. I have the perf_analyzer running cmd dispalyed in terminal and ran the same command string in another ternimal with triton serving using PA. Like
```
perf_analyzer -m ensemble -b 1 -u localhost:4110 -i http -f ensemble_config_default-results.csv --verbose-csv --measurement-interval 10000 --concurrency-range 25 --percentile 95 --input-data /ssd2/lyg/files/images/perf_jsons/track_person2_fire_ratio4_0.json --measurement-mode count_windows --measurement-request-count 200 --collect-metrics --metrics-url http://localhost:4112/metrics --metrics-interval 1000.0
```
But the throughput result was different. I got 60 in MA report but 75 in PA measurement. Any possible reason？

**Comment by nv-braf** [comment]
Is this a one off phenomenon or does this occur regularly? MA starts a server fresh before each profile, so it could be that you are observing warmup effects.

**Comment by monsterlyg** [comment]
I've known the reason. Thanks.
