### ISSUE TITLE
Model analyzer not showing full tag while model name too long

### ISSUE THREAD

**Issue by cezhang** [triton-inference-server/model_analyzer#745]
<img width="640" alt="image" src="https://github.com/triton-inference-server/model_analyzer/assets/5362164/2204c01c-a67f-4b7b-9936-42d130477183">

When the model has a long name, reports generated from model_analyzer cannot display tags correctly(hidden) for each models.

**Comment by nv-braf** [comment]
Thank you for bringing this to our attention. We will fix this in a future release.

**Comment by nv-braf** [comment]
This was fixed in the 23.09 release.
