### ISSUE TITLE
Pulling docker image inside the docker

### ISSUE THREAD

**Issue by miknyko** [triton-inference-server/model_analyzer#748]
I was running the model analyzer in the docker container which is pulled from office dockerhub.

And I ran `model-analyzer profile -f sweep.yaml --triton-launch-mode=docker` inside the container as per the tutorial.

However I saw model-analyzer is pulling again 
<img width="902" alt="image" src="https://github.com/triton-inference-server/model_analyzer/assets/41538890/b8ab46d4-c247-41f0-bc59-6b5b2892af1a">
Why is this happening ?

**Comment by nv-braf** [comment]
This is pulling the image for the tritonserver
