### ISSUE TITLE
Shared-memory size too small

### ISSUE THREAD

**Issue by wxthu** [triton-inference-server/model_analyzer#749]
When I profiled my model ensembles consisting of  3 model, I met the following error:
`Model add_config_1 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'add_config_1': version 1 is at UNAVAILABLE state: Internal: Unable to initialize shared memory key 'triton_python_backend_shm_region_3' to requested size (67108864 bytes). If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Each Python backend model instance requires at least 64MBs of shared memory. Error: No space left on device;`

However, I have launched docker container with params **_--shm-size_** ,I was confused,,,

**Comment by TanvirHundredOne** [comment]
use `--triton-docker-shm-size` flag for model-analyzer and set necessary shared memory size

**Comment by nv-braf** [comment]
The most likely reason is that the `--shm-size` of the docker container is set too small.
