### ISSUE TITLE
Illegal configuration ensemble model, when a config.pbtxt of a submodel is auto generated

### ISSUE THREAD

**Issue by SDJustus** [triton-inference-server/model_analyzer#791]
Hi folks,

trying out the model analyzer I noticed, that illegal configurations occur, when autogenerating a config for an ONNX-Model. 
This happens due to the max_batch_size, which is set to 1 form my ensemble model and is set to 4 (along with the prefered_batch_size) for the ONNX Model by Triton, since this is the default for this backend...

Is it expected behaviour for the configs generated by the model analyzer to be illegal in this case, since this configuration is deployable on Triton and works?

**Comment by SDJustus** [comment]
I think this is due to the model_analyzer trying to set the max_batch_size of the submodel to 1 while there is an dynamic_batching entry autogenerated.
```
dynamic_batching {
  preferred_batch_size: 4
}
```

**Comment by tgerdesnv** [comment]
What you are describing makes sense and sounds like a bug. There is code that tries to avoid illegal combinations, but something around autogeneration of configs and/or interaction with ensembles may be misbehaving. 

It would be helpful to have a simple repro of the issue. I don't need a model, but any configs or the CLI options you sent into MA would help me to reproduce and fix the issue.

**Comment by SDJustus** [comment]
I'll get a minimal example tomorrow. :)

**Comment by SDJustus** [comment]
[ensemble-model.zip](https://github.com/triton-inference-server/model_analyzer/files/13526078/ensemble-model.zip)

**Comment by SDJustus** [comment]
Thanks for digging further into it. Really appreciate the effort.
