### ISSUE TITLE
Color palette for plots

### ISSUE THREAD

**Issue by joaquincabezas** [triton-inference-server/model_analyzer#804]
Hi!

Regarding the current color palette for the plots, I would like to open a discussion. I am using the plots to communicate through messaging and custom reports and I find that the current color palette, while aesthetically pleasing, it's not the best for small devices or color-blindness.

I am proposing changing [_bar_colors](https://github.com/triton-inference-server/model_analyzer/blob/65bc1abf6129598d29bd2f477d6489e857ff672b/model_analyzer/plots/detailed_plot.py#L75-L81C10) to follow Okabe-Ito guidelines (https://jfly.uni-koeln.de/color/). I am using the following scheme:

```
        self._bar_colors = {
            "perf_server_queue": "#e69f00",
            "perf_server_compute_input": "#56b4e9",
            "perf_server_compute_infer": "#009e73",
            "perf_server_compute_output": "#f0e442",
            "perf_throughput": "#000000",
        }
```

An output example:
![image](https://github.com/triton-inference-server/model_analyzer/assets/1833086/2d9d825a-f1f3-49d9-b727-9b70ed83f909)

I've also noticed that the init method allows a 'bar_width' argument (even if it is not used in any call). I wonder if a 'bar_colors' argument would make sense or it is unnecessary complexity (defaulting to one particular color palette, maybe the current one, but allowing a few others).

Thanks!

**Comment by dyastremsky** [comment]
Thanks for this suggestion! Closing due to the related pull request being merged.
