### ISSUE TITLE
Bug: Capture gpu metrics is true even when the cpu_only is true, and the always_report_gpu_metrics is false

### ISSUE THREAD

**Issue by juanma9613** [triton-inference-server/model_analyzer#816]
There's an issue with a line of code which forces triton to try to collect gpu metrics even when a model is cpu only and I don't have a gpu available:

https://github.com/triton-inference-server/model_analyzer/blob/main/model_analyzer/record/metrics_manager.py#L255

Wrong:

        capture_gpu_metrics = (
            run_config.cpu_only() and not self._config.always_report_gpu_metrics
        )

Good:

        capture_gpu_metrics = (
            self._config.always_report_gpu_metrics or not run_config.cpu_only() 
        )

**Comment by tgerdesnv** [comment]
Thanks, I will look into this soon and fix.

**Comment by dyastremsky** [comment]
Thanks for this suggestion! Closing due to the related pull request being merged.
