### ISSUE TITLE
Confusing warning Config sweep parameters are ignored in the "remote" mode

### ISSUE THREAD

**Issue by juanma9613** [triton-inference-server/model_analyzer#817]
I  found this warning which is very confusing for the remote mode. Is that something that should be removed?:
https://github.com/triton-inference-server/model_analyzer/blob/main/model_analyzer/triton/server/server_factory.py#L167

[Model Analyzer] WARNING: Config sweep parameters are ignored in the "remote" mode because Model Analyzer does not have access to the model repository of the remote Triton Server.

That's doesn't seem to be true, I checked the triton endpoint for the config of the model and indeed the model_analyzer is changing the dynamic_batch and instance count parameters. The only thing that users need to do as mentioned here https://github.com/triton-inference-server/model_analyzer/blob/main/docs/launch_modes.md#remote is to enable --model-control-mode explicit in triton.

**Comment by tgerdesnv** [comment]
@nv-braf

**Comment by juanma9613** [comment]
Hi @nv-braf do you have any updates regarding this question? Is it true that in the remote mode, the model analyzer will still change the configuration of the remote tritonServer?

Thanks

**Comment by tgerdesnv** [comment]
Apologies for the delay @juanma9613. @nv-braf is dealing with some medical issues and this slipped through the cracks.

Yes, in remote mode Model Analyzer can change the configuration on the remote Triton Server. The warning that is printed is incorrect. There is a ticket to clean that up along with a few other incorrect warnings.
