### ISSUE TITLE
Memory leak when testing with GRPC

### ISSUE THREAD

**Issue by eladamittai** [triton-inference-server/model_analyzer#823]
Hello, I'm trying to run model analyzer on a remote torch model using GRPC, and every time the triton container resets from a segmentation fault. I tried to not add more model instances on the same GPU to use less memory, but it kept happening. In production the request count is identical to the request count during the analysis, but it doesn't recieve the memory leak. 

Details:
Triton version: 22.05
Model_analyzer version: 23.09
GPU: Tesla a-100

Model analyzer Config.yaml:

client_protocol: grpc
triton_launch_mode: remote
perf_analyzer_timeout: 4000
run_config_search_mode: brute
run_config_search_max_concurrency: 64
objectives:
   - perf_throughput
profile_models:
 grpc_model:
     model_config_parameters:
         max_batch_size: [8, 16, 32, 64, 96, 128, 150]
          dynamic_batching:
               preferred_batch_size: [[8], [16], [32], [64], [96], [128], [150]]                max_queue_delay_microseconds: [500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
perf_analyzer_flags:
   measurement-interval: 10000
   shape:
      - input:48000
      - attention:48000
   input-data: data.json
   measurement-mode: count_windows
    measurement-request-count: 70

**Comment by nv-braf** [comment]
If possible can you try running in local mode and see if the seg faults are still occurring?

**Comment by eladamittai** [comment]
Hey, I tried the same thing on a different model and it worked, so I guess there was a problem with the model. Thanks!
