### ISSUE TITLE
detailed report not generating

### ISSUE THREAD

**Issue by riyajatar37003** [triton-inference-server/model_analyzer#879]
this is the config.yaml

`model_repository: /tmp/models
run_config_profile_models_concurrently_enable: true
override_output_model_repository: true
run_config_search_mode: automatic
run_config_search_max_instance_count: 8
output_model_repository_path: /app/ma_outputs1
export_path: /app/ma_outputs2
profile_models:
  model_onnx:
    perf_analyzer_flags:
      input-data: "zero"
constraints:
  perf_latency_p99:
    max: 100`

only summaries are generated , detailed report for each config is not generated , what is  the reason?

**Comment by nv-braf** [comment]
https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config_search.md#multi-model-search-mode
