### ISSUE TITLE
Model_analyzer 1.42 creating config with kind_gpu only

### ISSUE THREAD

**Issue by Kanupriyagoyal** [triton-inference-server/model_analyzer#927]
I am using model analyzer 1.42 and server r24.07
1.https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#cli-and-yaml-config-options

# List of composing models that should be profiled using CPU instances only
cpu_only_composing_models: <comma-delimited-string-list>
```
Can only specify --cpu-only-composing-models for ensemble or BLS models.??
```

Not able to use as command line options - But able to use it in yaml 
 # Specifies which metric(s) are to be collected.
[ collect_cpu_metrics: <bool> | default: false ]
```
model-analyzer: error: unrecognized arguments: --collect_cpu_metrics
model-analyzer: error: unrecognized arguments: --collect_cpu_metrics true
```
```
model-analyzer profile --triton-launch-mode remote --client-protocol grpc --triton-grpc-endpoint x.xx.xx.xx:8001 --triton-metrics-url http://x.xx.xx.xx:8002/metrics --profile-models model1 --output-model-repository-path out_models --override-output-model-repository
```

2. I don't have GPU in my system:

```
[Model Analyzer] Creating model config: model1_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer] 
[Model Analyzer] Model model1_config_0 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'model1': version 1 is at READY state: Invalid argument: instance group model1_0 of model model1 has kind KIND_GPU but server does not support GPUs;
```
How in quick search mode it will take KIND_CPU instance only. How to make sure that model runs only on cpu instance.

How to avoid gpu metrics warnings also

**Comment by nv-braf** [comment]
When on the CLI the command is `--collect-cpu-metrics` (dashes instead of underscores).

**Comment by Kanupriyagoyal** [comment]
[#805 Questions regarding config search](https://github.com/triton-inference-server/model_analyzer/issues/805)
In this 2nd point. Always getting instance as kind_cpu. 
In my case its happening reverse as I am getting 'KIND_GPU', which parameter i can pass in command line to make sure it will create KIND_CPU instance.
```
[Model Analyzer] Creating model config: model1_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer] 
[Model Analyzer] Model model1_config_0 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'model1': version 1 is at READY state: Invalid argument: instance group model1_0 of model model1 has kind KIND_GPU but server does not support GPUs;
```

**Comment by Kanupriyagoyal** [comment]
@nv-braf is there any option to pass in command line so that it can take KIND_CPU instance only!!

**Comment by nv-braf** [comment]
Not on the command line, but you can specify `cpu_only` as a flag to the model in the YAML file. Please see our documentation for an example on how to do this: [https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#cpu_only]https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#cpu_only)

**Comment by Kanupriyagoyal** [comment]
@nv-braf Thanks cpu_only flag i had tried and working fine. I was looking for command line option.
