### ISSUE TITLE
Potential Infinite loop 

### ISSUE THREAD

**Issue by ynb10** [triton-inference-server/model_analyzer#936]
**Description**
I have identified a potential issue in the code that may cause an infinite loop. The while() loop in question lacks a clear termination condition or any break statements.

**Code**
model_analyzer/monitor/dcgm/dcgm_field_helpers.py/line:522
https://github.com/triton-inference-server/model_analyzer/blob/r24.09/model_analyzer/monitor/dcgm/dcgm_field_helpers.py

**Triton Information**
r24.09

Adding a condition or break mechanism to ensure the loop can terminate as expected. Looking for any suggestions on the same.

**Comment by nv-braf** [comment]
I believe this is just test code that is never executed in a run of MA.

**Comment by ynb10** [comment]
Okay, got it!
Thanks for the quick reply!
